# Site settings
title: Kynrai Ltd
email: kynra@gmail.com
description: "Technology consultancy" # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kynrai.github.io"

twitter_username: kynrai
github_username: kynrai

# Build settings
markdown: kramdown
